<a href="https://colab.research.google.com/github/jirachaya-bam/Data_viz/blob/main/More_advaanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
ที่เรียนไปแล้วมี 1 ตัวคือ list หน้าตาประมาณนี้

#Dictionary

สามารถ index ด้วยอะก็ได้ แต่ลำดับจะหายไป

In [1]:
ex_dict = {'a ' :10, '1' :1, 'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [2]:
ex_dict['stat']

5

In [7]:
ex2_dict = {1:'one' , 2:'two' , 3:'three'}

In [8]:
ex2_dict[2]

'two'

#การเพิ่มสมาชิก

In [9]:
ex2_dict[0] = 'zero'

In [10]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่ง

In [12]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [13]:
for index in ex2_dict.keys():
      print(index)

1
2
3
0


In [14]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [15]:
 index
 

0

dict เอาไปใช้ร่วมกับ dataframe 

numpy คือ package ที่ทำงานเกี่ยวกับ  array ของตัวเลข (ที่มีคนเขียนขึ้นมาและนิยมใช้)

numpy -> number python


In [16]:
import numpy #วิธีเรียกใช้งาน package

#สร้าง numpy array

In [18]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


#การชี้ค่าใน numpy array

In [19]:
ex_2d_array[1,2]

0.3

In [25]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list
print(len(list_x))

print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


#Operations

In [26]:
ex2_2d_array = numpy .array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [27]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [28]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [29]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]

list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [31]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

In [30]:
ex_2d_array  * ex2_2d_array #เอาตำแหน่งเดียวมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

matix multiplication (dot product)

In [32]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [35]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat)

[[5.2 4.5]
 [9.1 0.3]]


In [36]:
numpy.linalg.det(dot_mat)

-39.389999999999986

search google -> stackoverflow หรือ web ของ  package สำหรับ operation อื่นๆ

###matrix slicing

In [37]:
print(ex_2d_array)


[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [38]:

ex_2d_array[1,1:]

array([0.1, 0.3])

In [39]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

##random,ones,zeros 

HW 5 เขียน function คูณ matrix

แล้ว test  กับ matrix

-(2,3)*(3,2)
-(4,4)*(4,1)
-(2,2)*(2,2)