<a href="https://colab.research.google.com/github/jirachaya-bam/Data_viz/blob/main/More_advaanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
ที่เรียนไปแล้วมี 1 ตัวคือ list หน้าตาประมาณนี้

#Dictionary

สามารถ index ด้วยอะก็ได้ แต่ลำดับจะหายไป

In [ ]:
ex_dict = {'a ' :10, '1' :1, 'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = {1:'one' , 2:'two' , 3:'three'}

In [ ]:
ex2_dict[2]

'two'

#การเพิ่มสมาชิก

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่ง

In [ ]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys():
      print(index)

1
2
3
0


In [ ]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [ ]:
 index
 

0

dict เอาไปใช้ร่วมกับ dataframe 

numpy คือ package ที่ทำงานเกี่ยวกับ  array ของตัวเลข (ที่มีคนเขียนขึ้นมาและนิยมใช้)

numpy -> number python


In [ ]:
import numpy #วิธีเรียกใช้งาน package

#สร้าง numpy array

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


#การชี้ค่าใน numpy array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list
print(len(list_x))

print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


#Operations

In [ ]:
ex2_2d_array = numpy .array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]

list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [ ]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

In [ ]:
ex_2d_array  * ex2_2d_array #เอาตำแหน่งเดียวมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

matix multiplication (dot product)

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [ ]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat)

[[5.2 4.5]
 [9.1 0.3]]


In [ ]:
numpy.linalg.det(dot_mat)

-39.389999999999986

search google -> stackoverflow หรือ web ของ  package สำหรับ operation อื่นๆ

###matrix slicing

In [ ]:
print(ex_2d_array)


[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:

ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

##random,ones,zeros 

HW 5 เขียน function คูณ matrix

แล้ว test  กับ matrix

-(2,3)*(3,2)
-(4,4)*(4,1)
-(2,2)*(2,2)

In [1]:
import numpy as np

In [2]:
mat_T = np.array([[1,4,2],[2,8,7]])
mat_T
#Matrix 2*3

array([[1, 4, 2],
       [2, 8, 7]])

In [3]:
mat_O = np.array([[4,2],[6,8],[2,1]])
mat_O
#Matrix 3*2

array([[4, 2],
       [6, 8],
       [2, 1]])

In [4]:
mat_E = np.array([[1,5,4,3],[5,2,1,4],[9,6,2,4],[1,3,2,4]])
mat_E
#Matrix 4*4

array([[1, 5, 4, 3],
       [5, 2, 1, 4],
       [9, 6, 2, 4],
       [1, 3, 2, 4]])

In [5]:
mat_I = np.array([[1],[4],[5],[7]])
mat_I
#Matrix 4*1

array([[1],
       [4],
       [5],
       [7]])

In [6]:
mat_P = np.array([[5,1],[4,2]])
mat_P
#Matrix 2*2 

array([[5, 1],
       [4, 2]])

In [7]:
mat_A = np.array([[1,8],[7,3]])
mat_A

array([[1, 8],
       [7, 3]])

**Create Function Multiply Matrix**

In [8]:
def mul_mat(T, O):
    E = [[0 for row in range(len(O[0]))] for col in range(len(T))]
    for i in range(len(T)):
        for j in range(len(O[0])):
            for k in range(len(O)):
                E[i][j] += T[i][k]*O[k][j]
    r = np.matrix(E)
    return r

In [9]:
mul_mat(mat_T,mat_O)
#(2,3)*(3,2)

matrix([[32, 36],
        [70, 75]])

In [10]:
mul_mat(mat_E,mat_I)
#(4,4)*(4,1)

matrix([[62],
        [46],
        [71],
        [51]])

In [11]:
mul_mat(mat_P,mat_A)
#(2,2)*(2,2),

matrix([[12, 43],
        [18, 38]])

**ตรวจสอบความถูกต้อง**

In [12]:
np.dot(mat_T,mat_O)
#(2,3)*(3,2)

array([[32, 36],
       [70, 75]])

In [13]:
np.dot(mat_E,mat_I)
#(4,4)*(4,1)

array([[62],
       [46],
       [71],
       [51]])

In [14]:
np.dot(mat_P,mat_A)
#(2,2)*(2,2)

array([[12, 43],
       [18, 38]])